### ISSUE TITLE
兄弟这篇文章的开源代码在哪里呀？

### ISSUE THREAD

**Issue by zzzendurance** [lijfrank-open/CFN-ESA#1]
”CFN-ESA: A Cross-Modal Fusion Network with Emotion-Shift Awareness for Dialogue Emotion Recognition“
Jiang Li ˙ID, Yingjian Liu, Xiaoping Wang ˙ID, Senior Member, IEEE, and Zhigang Zeng ˙ID, Fellow, IEEE
这篇论文的代码是开源的吗？我貌似没找到其他可靠的，就兄弟你这里有了

**Comment by lijfrank** [comment]
> ”CFN-ESA: A Cross-Modal Fusion Network with Emotion-Shift Awareness for Dialogue Emotion Recognition“ Jiang Li ˙ID, Yingjian Liu, Xiaoping Wang ˙ID, Senior Member, IEEE, and Zhigang Zeng ˙ID, Fellow, IEEE 这篇论文的代码是开源的吗？我貌似没找到其他可靠的，就兄弟你这里有了

感谢您的关注。这篇论文还是投稿中，暂时还没开源。不过，后期我们会开源。
