### ISSUE TITLE
代码复线

### ISSUE THREAD

**Issue by gravity5212** [lijfrank-open/CFN-ESA#3]
您好，想请问一下代码复现的流程是怎样的呀，想要复现一下优秀的论文！期待你们的回复

**Comment by lijfrank** [comment]
运行run_x.py即可

**Comment by gravity5212** [comment]
你好，在run_MELD.py，MELD_path = '/home/lijfrank/code/dataset/MELD_features/meld_multi_features_mmgcn_cosmic.pkl' 中的meld_multi_features_mmgcn_cosmic.pkl并没有给出，请问您可以给我提供数据的下载地址吗

**Comment by gravity5212** [comment]
你好，我并没有找到复现所需要的数据集，请问你们可以提供吗😃😃

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月12日 02:49 |
| 收件人 | lijfrank-open/CFN-ESA ***@***.***> |
| 抄送人 | gravity5212 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [lijfrank-open/CFN-ESA] 代码复线 (Issue #3) |

运行run_x.py即可
