### ISSUE TITLE
MELD数据集性能表中disgust一类结果（Results of the disgust category in the MELD performance table）

### ISSUE THREAD

**Issue by xueyuG** [lijfrank-open/CFN-ESA#4]
中文：作者您好，有个问题请教。在MELD结果表中，加粗的是五次实验的最优结果，那么下一行是五次实验的平均结果吗。如果是的话，在disgust这一类中，最优结果为26.92，平均结果为30.14，是否是数据录入出了问题。希望得到您的回答，万分感谢！
English: Dear author, I have a question. In the MELD result table, the bolded result is the best result of five experiments. Is the next row the average result of the five experiments? If so, in the disgust category, the best result is 26.92 and the average result is 30.14. Is there a problem with the data entry? I hope to get your answer. Thank you very much!

**Comment by lijfrank** [comment]
> 中文：作者您好，有个问题请教。在MELD结果表中，加粗的是五次实验的最优结果，那么下一行是五次实验的平均结果吗。如果是的话，在disgust这一类中，最优结果为26.92，平均结果为30.14，是否是数据录入出了问题。希望得到您的回答，万分感谢！ English: Dear author, I have a question. In the MELD result table, the bolded result is the best result of five experiments. Is the next row the average result of the five experiments? If so, in the disgust category, the best result is 26.92 and the average result is 30.14. Is there a problem with the data entry? I hope to get your answer. Thank you very much!

你好，没有录入问题。我们的最优结果指的是weighted F1分数最优，而不是某一类情绪的F1分数。某一类的F1分数并不一定是越大越能让weighted F1越好。

**Comment by xueyuG** [comment]
> > 中文：作者您好，有个问题请教。在MELD结果表中，加粗的是五次实验的最优结果，那么下一行是五次实验的平均结果吗。如果是的话，在disgust这一类中，最优结果为26.92，平均结果为30.14，是否是数据录入出了问题。希望得到您的回答，万分感谢！ English: Dear author, I have a question. In the MELD result table, the bolded result is the best result of five experiments. Is the next row the average result of the five experiments? If so, in the disgust category, the best result is 26.92 and the average result is 30.14. Is there a problem with the data entry? I hope to get your answer. Thank you very much!
> 
> 你好，没有录入问题。我们的最优结果指的是weighted F1分数最优，而不是某一类情绪的F1分数。某一类的F1分数并不一定是越大越能让weighted F1越好。

感谢作者，了解了。所以粗体是wF1最优的一次实验的结果，下一行是五次实验的平均结果，是这个样子吗

**Comment by lijfrank** [comment]
> > > 中文：作者您好，有个问题请教。在MELD结果表中，加粗的是五次实验的最优结果，那么下一行是五次实验的平均结果吗。如果是的话，在disgust这一类中，最优结果为26.92，平均结果为30.14，是否是数据录入出了问题。希望得到您的回答，万分感谢！ English: Dear author, I have a question. In the MELD result table, the bolded result is the best result of five experiments. Is the next row the average result of the five experiments? If so, in the disgust category, the best result is 26.92 and the average result is 30.14. Is there a problem with the data entry? I hope to get your answer. Thank you very much!
> > 
> > 
> > 你好，没有录入问题。我们的最优结果指的是weighted F1分数最优，而不是某一类情绪的F1分数。某一类的F1分数并不一定是越大越能让weighted F1越好。
> 
> 感谢作者，了解了。所以粗体是wF1最优的一次实验的结果，下一行是五次实验的平均结果，是这个样子吗

嗯嗯。
