### ISSUE TITLE
Alternative Download Links for IEMOCAP and MELD Datasets

### ISSUE THREAD

**Issue by vanntc711** [lijfrank-open/CFN-ESA#5]
I am writing to request alternative download links for the IEMOCAP and MELD datasets. The current links provided are on Baidu Disk, which is difficult for international users to access.

**Comment by lijfrank** [comment]
> I am writing to request alternative download links for the IEMOCAP and MELD datasets. The current links provided are on Baidu Disk, which is difficult for international users to access.

I apologize for getting back to you now. Google Drive: https://drive.google.com/drive/folders/1l_ex1wnAAMpEtO71rjjM1MKC7W_olEVi?usp=drive_link
