### ISSUE TITLE
关于IEMOCAP和MELD的pkl文件

### ISSUE THREAD

**Issue by hardlucky2023** [lijfrank-open/CFN-ESA#7]
作者您好，我是刚刚接触ERC这个领域，目前找到的代码都是直接给到了iemocap和meld两个数据集的已经提取好的特征pkl文件，这里想向您请教下有没有如何针对原始数据集不同模态的特征提取方法的代码，希望能收到您的回复。

**Comment by lijfrank** [comment]
> 作者您好，我是刚刚接触ERC这个领域，目前找到的代码都是直接给到了iemocap和meld两个数据集的已经提取好的特征pkl文件，这里想向您请教下有没有如何针对原始数据集不同模态的特征提取方法的代码，希望能收到您的回复。

你好，我们参考了MMGCN和COSMIC的工作，你可以试试找他们要一下。

**Comment by hardlucky2023** [comment]
好的，谢谢您
